language: cpp

notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          update: true
          packages:
            - cmake

    - os: windows

before_install:
    - cmake .

install:
    - mkdir build
    - cmake --build .

script:
    - ctest -T test -C debug