language: cpp

notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          upgrade: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake

    - os: windows

install:
    - cmake .

script:
    - mkdir build
    - cmake --build .